name: shortener
description: A URL Shortener
branding:
  icon: link
  color: red
inputs:
  json-database-path:
    description: path to the json database file
    required: false
    default: ./url.json
  not-found-file-path:
    description: path to the 404.html file
    required: false
    default: ./404.html
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Run Test Script
      id: shortener-script
      uses: actions/github-script@v6
      with:
        result-encoding: string
        script: |
          const { ACTION_PATH } = process.env;
          const script = require(`${ACTION_PATH}/on-issue.js`);
          return await script({ github, context, core, io, exec, require });
        env:
          ACTION_PATH: ${{ inputs.json-database-path }}
          # ACTION_PATH: ${{ github.action_path }}
    # - name: Upload Artifact
    #   if: ${{ steps.shortener-script.outputs.result == "success:on-push" }}
    #   uses: actions/upload-pages-artifact@v1
    #   with:
    #     path: ./_site/
    # - name: Deploy to GitHub Pages
    #   if: ${{ steps.shortener-script.outputs.result == "success:on-push" }}
    #   uses: actions/deploy-pages@v1
